deployment:
  replicas: 1
  service:
    name: ws-api-service
    port: 8080
    targetPort: 8080
    type: NodePort
  container:
    port: 80
  image:
    tag: bretfisher/wordsmith-web
  pullpolicy: Always
  name: ws-api